### ISSUE TITLE
Webpack stats settings hide Stylelint errors in Riot components

### ISSUE THREAD

**Issue by lxndrdagreat** [epandco/unthink-cli#17]
Current `stats` settings mean that when there is a stylelint error, all that is shown in the console is the webpack "failed to compile" message.

**Comment by lxndrdagreat** [comment]
Example:

```scss
  <style type="scss">
    :host {
      background-color: $background;
    }
```
